### ISSUE TITLE
java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by sveltema** [mariuswatz/modelbuilderMk2#2]
Running the UGeoGroup_01 (modelbuilderMk2-0156-20140804.zip) results in a divide by zero exception in UGeo.removeDupl().  Perhaps at line 214? 

```
 if((cnt++)%modulus==0) 
```

**\* Stacktrace

```
    00:00 UMB.setGraphics: PGraphics3D (is3D=true)
    00:00 [5    <0.3536,0.3536,-0.5000> <0.3536,-0.3536,-0.5000>    <-0.3536,-0.3536,-0.5000>   <-0.3536,0.3536,-0.5000>    <0.3536,0.3536,-0.5000>]
    00:00 [5    <0.3536,0.3536,0.5000>  <0.3536,-0.3536,0.5000> <-0.3536,-0.3536,0.5000>    <-0.3536,0.3536,0.5000> <0.3536,0.3536,0.5000>]
    java.lang.RuntimeException: java.lang.ArithmeticException: / by zero
        at com.jogamp.common.util.awt.AWTEDTExecutor.invoke(AWTEDTExecutor.java:58)
        at jogamp.opengl.awt.AWTThreadingPlugin.invokeOnOpenGLThread(AWTThreadingPlugin.java:103)
        at jogamp.opengl.ThreadingImpl.invokeOnOpenGLThread(ThreadingImpl.java:206)
        at javax.media.opengl.Threading.invokeOnOpenGLThread(Threading.java:172)
        at javax.media.opengl.Threading.invoke(Threading.java:191)
        at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:541)
        at processing.opengl.PJOGL.requestDraw(PJOGL.java:688)
        at processing.opengl.PGraphicsOpenGL.requestDraw(PGraphicsOpenGL.java:1651)
        at processing.core.PApplet.run(PApplet.java:2256)
        at java.lang.Thread.run(Thread.java:745)
    Caused by: java.lang.ArithmeticException: / by zero
        at unlekker.mb2.geo.UGeo.removeDupl(Unknown Source)
        at unlekker.mb2.geo.UGeo.quadstrip(Unknown Source)
        at unlekker.mb2.geo.UGeo.quadstrip(Unknown Source)
        at unlekker.mb2.geo.UGeoGenerator.meshPlane(Unknown Source)
        at UGeoGroup_01.build(UGeoGroup_01.java:102)
        at UGeoGroup_01.setup(UGeoGroup_01.java:58)
        at processing.core.PApplet.handleDraw(PApplet.java:2361)
        at processing.opengl.PJOGL$PGLListener.display(PJOGL.java:862)
        at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:665)
        at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:649)
        at javax.media.opengl.awt.GLCanvas$10.run(GLCanvas.java:1289)
        at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1119)
        at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:994)
        at javax.media.opengl.awt.GLCanvas$11.run(GLCanvas.java:1300)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:302)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:733)
        at java.awt.EventQueue.access$200(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:694)
        at java.awt.EventQueue$3.run(EventQueue.java:692)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:703)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by mariuswatz** [comment]
I get the same error, so something is definitely wrong. I'll look into it, thanks for bringing it to my attention.

Are you getting this error in code you're currently working on?

**Comment by mariuswatz** [comment]
Fixed in build 0158, just uploaded. The bug was in UGeo.removeDupl(). Thanks for the report!

**Comment by sveltema** [comment]
Thanks!  I thought that %modulus was causing it, but wasn't really sure if the 0 value was a valid case or not.

**Comment by mariuswatz** [comment]
Your assumption was right on, a reminder to always check both division and modulus operations for div by zero issues.
